ForumDiskusi/urls.py
from django.urls import path
from .views import show_book_discussion, show_discussion_comment, create_discussion, get_comment_json, add_comment_ajax

from .views import create_discussion_flutter ,create_comment_flutter, show_json_discussions, show_json_comments


app_name = 'ForumDiskusi'

urlpatterns = [
    path('discussions/book=<str:book_id>', show_book_discussion, name='show_book_discussion'),
    path('discussions/topic=<str:discussion_id>', show_discussion_comment, name='show_discussion_comment'),
    path('discussions/create-discussion/<str:book_id>', create_discussion, name='create_discussion'),
    path('discussios/get-comment/<str:discussion_id>', get_comment_json, name='get_comment_json'),
    path('discussions/create-ajax/<str:discussion_id>', add_comment_ajax, name='add_comment_ajax'),

    path('discussions/json-discussions/<str:book_id>', show_json_discussions, name='show_json_discussions'),
    # path('discussions/json-discussions/', show_json_discussions, name='show_json_discussions'),

    path('discussions/json-comments/<str:discussion_id>', show_json_comments, name='show_json_comments'), #filter
    # path('discussions/json-comments/', show_json_comments, name='show_json_comments'),

    path('discussions/create-discussion-flutter/<str:book_id>', create_discussion_flutter, name='create_discussion_flutter'),
    # path('discussions/create-discussion-flutter/', create_discussion_flutter, name='create_discussion_flutter'),
    path('discussions/create-comment-flutter/<str:discussion_id>', create_comment_flutter, name='create_comment_flutter'),
]

README/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("KatalogBuku.urls")),
    path("__reload__/", include("django_browser_reload.urls")),  # new
    path("profile/", include("UserProfile.urls")),
    path("review/", include("ReviewBuku.urls")),
    path("", include("ForumDiskusi.urls")),
    path("read-book/", include("pinjambuku.urls")),
]

ForumDiskusi/models.py
from django.db import models

import uuid

app_name = 'ForumDiskusi'


class BookDiscussion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    book = models.ForeignKey('KatalogBuku.Book', on_delete=models.CASCADE, related_name='current_book')
    user = models.ForeignKey('UserProfile.Profile', on_delete=models.CASCADE, related_name='user_discussions')
    username = models.CharField(max_length=255, default="")
    title = models.CharField(max_length=255)
    content = models.TextField(default="")
    upvotes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)



class DiscussionComment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    discussion = models.ForeignKey('BookDiscussion', on_delete=models.CASCADE, related_name='current_discussion')
    user = models.ForeignKey('UserProfile.Profile', on_delete=models.CASCADE, related_name='user_comments')
    username = models.CharField(max_length=255, default="")
    title = models.CharField(max_length=255)
    content = models.TextField(default="")
    upvotes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

ForumDiskusi/forms.py
from django.forms import ModelForm
from .models import BookDiscussion, DiscussionComment

class BookDiscussionForm(ModelForm):
    class Meta:
        model = BookDiscussion
        fields = ['title', 'content']

ForumDiskusi/views.py
import datetime
import json
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

#forms
from django.http import HttpResponseRedirect
from ForumDiskusi.forms import BookDiscussionForm
from django.urls import reverse

from UserProfile.models import Profile
from .models import BookDiscussion, DiscussionComment
from KatalogBuku.models import Book
from django.utils import timezone



@login_required(login_url='/login/')
def show_book_discussion(request, book_id):
    discussions = BookDiscussion.objects.filter(book_id=book_id) # nanti difilter berdasarkan book_id

    search_query = request.GET.get('search')  # Get the search query from the request

    if search_query:
        discussions = discussions.filter(Q(title__icontains=search_query))

    context = {
        'discussions': discussions,
        'user': request.user,
        'book_id': book_id,
        'book': Book.objects.get(id=book_id),
    }
    # print(discussions)
    return render(request, "discussion_forum.html", context)

from django.views.decorators.csrf import csrf_exempt

from django.db.models import Q



@login_required(login_url='/login/')
def show_discussion_comment(request, discussion_id):
    comments = DiscussionComment.objects.filter(discussion_id = discussion_id)
    search_query = request.GET.get('search')

    if search_query:
        comments = comments.filter(Q(title__icontains=search_query))
    
    context = {
        'comments': comments,
        'user': request.user,
        'discussion_id': discussion_id,
        'discussion': BookDiscussion.objects.get(id=discussion_id),
    }
    return render(request, "discussion_comments.html", context)

@login_required(login_url='/login/')
def create_discussion(request, book_id):
    book = Book.objects.get(id=book_id)

    if request.method == 'POST':
        form = BookDiscussionForm(request.POST)
        if form.is_valid():
            discussion = form.save(commit=False)
            discussion.book = book
            discussion.user = Profile.objects.filter(user=request.user).first()
            discussion.save()
            return redirect('ForumDiskusi:show_book_discussion', book_id=book_id)
    else:
        form = BookDiscussionForm()

    context = {
        'form': form,
        'book_id': book_id,
    }
    return render(request, "create_discussion.html" , context)


from django.core import serializers

def get_comment_json(request, discussion_id):
    comment = DiscussionComment.objects.filter(discussion_id = discussion_id)
    return HttpResponse(serializers.serialize('json', comment))

@csrf_exempt
def add_comment_ajax(request, discussion_id):
    if request.method == 'POST':
        discussion = BookDiscussion.objects.filter(id = discussion_id).first()
        user = Profile.objects.filter(user=request.user).first()
        user_name = user.username
        title = request.POST['title']
        content = request.POST['content']
        upvotes = 0
        created_at_iso8601 = datetime.datetime.now().isoformat()
        created_at = created_at_iso8601.replace("T", " ")[:-10]
        # print(created_at)
        

        comment = DiscussionComment.objects.create(
            user=user,
            username= user_name,
            discussion = discussion,
            title=title,
            content=content,
            upvotes=upvotes,
            created_at=created_at,
        )
        comment.save()

        response_data = {
            'status': 'CREATED',
            # 'user_name': user_name,
        }

        
        return HttpResponse(response_data, status=201)
    return HttpResponseNotFound()


# def show_json_discussions(request):
#     data = BookDiscussion.objects.all()
#     return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_discussions(request, book_id):
    data = BookDiscussion.objects.filter(book_id = book_id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_comments(request, discussion_id):
    data = DiscussionComment.objects.filter(discussion_id = discussion_id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_discussion_flutter(request, book_id):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        # new_product = Item.objects.create(
        #     user = request.user,
        #     name = data["name"],
        #     amount = int(data["amount"]),
        #     price = int(data["price"]),
        #     description = data["description"]
        # )

        new_discussion = BookDiscussion.objects.create(
            user = Profile.objects.filter(user=request.user).first(),
            book = Book.objects.filter(id=book_id).first(),
            username = Profile.objects.filter(user=request.user).first().username,
            title = data["title"],
            content = data["content"],
            upvotes = 0,
            created_at = timezone.now(),
        )

        new_discussion.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt  
def create_comment_flutter(request, discussion_id):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_comment = DiscussionComment.objects.create(
            user = Profile.objects.filter(user=request.user).first(),
            discussion = BookDiscussion.objects.filter(id=discussion_id).first(),
            username = Profile.objects.filter(user=request.user).first().username,
            title = data["title"],
            content = data["content"],
            upvotes = 0,
            created_at = timezone.now(),
        )

        new_comment.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

ForumDiskusi/templates/create_discussion.html
{% extends 'base-bootstrap.html' %}

{% load static %}
{% block content %}
{% include 'header.html' %}
<style>
    .footer {
        position: absolute;
        bottom: auto;
        width: 100%;
        text-align: center;
    }
    

    html, body {
margin: 0;
padding: 0;
height: 100%;
}

.body {
display: flex;
flex-direction: column;
min-height: 100%;
}

            .wrapper {
        min-height: 100%;
        display: flex;
        flex-direction: column;
    }

    .content {
        flex: 1; /* This pushes the footer to the bottom */
    }
</style>
<body>
    <div class="wrapper">
        <div class="content">
            <h1 style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;">Add New Discussion</h1>

    <form method="POST" style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Discussion" class="btn btn-success btn-sm" style="background-color: #5068A9;"/>
                </td>
            </tr>
        </table>
    </form>
    <footer>
        {% include 'footer.html' %}
    </footer>
        </div>
        </div>
        
</body>



    
        <!-- {% include 'footer.html' %} -->
    </div>
    

    {% endblock content %}

ForumDiskusi/templates/discussion_comments.html
{% extends 'base-bootstrap.html' %}

{% load static %}
{% block content %}
{% include 'header.html' %}

<h1 style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;">Discussion Comments</h1>

<h2 style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;">{{ discussion.title }}</h2>

<form style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;" method="GET" action="{% url 'ForumDiskusi:show_discussion_comment' discussion_id=discussion.id %}" class="form-inline">
    <div class="form-group">
        <input type="text" name="search" class="form-control" placeholder="Search Comments by Title">
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<button style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;" type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-bottom: 10px;">Add Comment</button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Comment</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title"></input>
                    </div>
                    <div class="mb-3">
                        <label for="content" class="col-form-label">Content:</label>
                        <textarea class="form-control" id="content" name="content"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Comment</button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="card-deck w-full" id="comment_cards"></div>
</div>




<script>
    async function getComments() {
        return fetch("{% url 'ForumDiskusi:get_comment_json' discussion_id=discussion.id %}").then((res) => res.json());
    }

    async function refreshComments() {
        const comments = await getComments();

        const commentCardsContainer = document.getElementById("comment_cards");
        commentCardsContainer.innerHTML = "";

        comments.forEach((comment) => {
            const card = document.createElement("div");
            card.classList.add("col-lg-4", "col-md-6", "mb-4");

            card.innerHTML = `
            <div class="card">
                <div class="card-body">
                <p class="card-text">by: ${comment.fields.name}</p>
                <h5 class="card-title">${comment.fields.title}</h5>
                <p class="card-text">${comment.fields.content}</p>
                <p class="card-text">Date: <span class="formatted-date">${comment.fields.created_at}</span></p>
             
                </div>
            </div>
            `;
            commentCardsContainer.appendChild(card);
            
        });

                // Select all elements with class 'formatted-date' and update their content
        const dateElements = document.querySelectorAll('.formatted-date');
        dateElements.forEach((element) => {
            // Get the original date value
            const originalDate = element.textContent;
            
            // Replace 'T' with a space
            const formattedDate = originalDate.replace('T', ' ').split('.')[0];

            // Update the content with the formatted date
            element.textContent = formattedDate;
        });
    }

    refreshComments();

    function addComment() {
        fetch("{% url 'ForumDiskusi:add_comment_ajax' discussion_id=discussion.id %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshComments);

        document.getElementById("form").reset();
        return false;
    }

    document.getElementById("button_add").onclick = addComment;
</script>
{% include 'footer.html' %}

{% endblock content %}

ForumDiskusi/templates/discussion_forum.html
{% extends 'base-bootstrap.html' %}

{% load static %}
{% block content %}
    {% include 'header.html' %}

    <div style="min-height: 500px">
        <h1 style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;">Forum Discussion</h1>

        <!-- Search bar form -->
        <form style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;" method="GET"
              action="{% url 'ForumDiskusi:show_book_discussion' book_id=book_id %}" class="form-inline">
            <div class="form-group">
                <input type="text" name="search" class="form-control" placeholder="Search by Title">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>

        <a style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;"
           href="{% url 'ForumDiskusi:create_discussion' book_id=book_id %}" class="btn btn-success btn-sm">
            Add New Discussion
        </a>

        <div class="row" style="margin-top: 20px; margin-bottom: 20px; margin-left: 20px; margin-right: 20px;">
            {% for discussion in discussions %}
                <div class="col-md-4 mb-3">
                    <div class="card custom-card">
                        <div class="card-body">
                            <p>{{ discussion.user.name }}</p>
                            <h2 class="card-title">{{ discussion.title }}</h2>
                            <p class="card-text">{{ discussion.content }}</p>
                            <td>
                                <a href="{% url 'ForumDiskusi:show_discussion_comment' discussion_id=discussion.id %}"
                                   class="btn btn-success btn-sm" style="background-color: #5068A9;">
                                    Comments
                                </a>
                            </td>


                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        </body>

        <style>
            .custom-card {
                height: 100%;
                margin: 10px;
            }

            .footer {
                position: absolute;
                bottom: auto;
                width: 100%;
                text-align: center;
            }

            body {
                height: 100%;
            }


        </style>
    </div>


    <div class="footer">
        {% include 'footer.html' %}
    </div>

{% endblock content %}