ForumDiskusi/urls.py
from django.urls import path
from .views import show_book_discussion, show_discussion_comment, create_discussion, get_comment_json, add_comment_ajax

from .views import create_discussion_flutter ,create_comment_flutter, show_json_discussions, show_json_comments


app_name = 'ForumDiskusi'

urlpatterns = [
    path('discussions/book=<str:book_id>', show_book_discussion, name='show_book_discussion'),
    path('discussions/topic=<str:discussion_id>', show_discussion_comment, name='show_discussion_comment'),
    path('discussions/create-discussion/<str:book_id>', create_discussion, name='create_discussion'),
    path('discussios/get-comment/<str:discussion_id>', get_comment_json, name='get_comment_json'),
    path('discussions/create-ajax/<str:discussion_id>', add_comment_ajax, name='add_comment_ajax'),

    path('discussions/json-discussions/<str:book_id>', show_json_discussions, name='show_json_discussions'),
    # path('discussions/json-discussions/', show_json_discussions, name='show_json_discussions'),

    path('discussions/json-comments/<str:discussion_id>', show_json_comments, name='show_json_comments'), #filter
    # path('discussions/json-comments/', show_json_comments, name='show_json_comments'),

    path('discussions/create-discussion-flutter/<str:book_id>', create_discussion_flutter, name='create_discussion_flutter'),
    # path('discussions/create-discussion-flutter/', create_discussion_flutter, name='create_discussion_flutter'),
    path('discussions/create-comment-flutter/<str:discussion_id>', create_comment_flutter, name='create_comment_flutter'),
]

KatalogBuku/urls.py
from django.urls import path
from .views import (
    index,
    get_books,
    get_categories,
    get_book_by_id,
    like_book,
    unlike_book,
    show_request_book,
    form_request_book,
    get_book_by_id_json,
)

app_name = "KatalogBuku"

urlpatterns = [
    path("", index, name="index"),
    path("books/", get_books, name="get_books"),
    path("books/category", get_categories, name="get_categories"),
    path("books/<str:book_id>", get_book_by_id, name="book_detail"),
    path("books/<str:book_id>/json", get_book_by_id_json, name="book_detail_json"),
    path("books/<str:book_id>/like", like_book, name="like_book"),
    path("books/<str:book_id>/unlike", unlike_book, name="unlike_book"),
    path("request/form", form_request_book, name="form_request_book"),
    path("request", show_request_book, name="show_request_book"),
]

README/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("KatalogBuku.urls")),
    path("__reload__/", include("django_browser_reload.urls")),  # new
    path("profile/", include("UserProfile.urls")),
    path("review/", include("ReviewBuku.urls")),
    path("", include("ForumDiskusi.urls")),
    path("read-book/", include("pinjambuku.urls")),
]

ReviewBuku/urls.py
from django.urls import path
from .views import *

app_name = "ReviewBuku"

urlpatterns = [
    path("", show_page_review, name="show_read_books"),
    path("add-review/<str:book_id>/", review_buku, name="review_buku"),
    path(
        "show-page-review-ajax/<str:book_id>/",
        show_page_review_ajax,
        name="show_page_review_ajax",
    ),
    path(
        "show-page-review-user-ajax/",
        show_page_review_user_ajax,
        name="show_page_review_user_ajax",
    ),
    path("get-reviews-json/", get_reviews_json, name="get_reviews_json"),
    path(
        "review-buku-flutter/",
        review_buku_flutter,
        name="review_buku_flutter",
    ),
]

KatalogBuku/models.py
from django.db import models
import uuid

app_name = 'KatalogBuku'


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    issued = models.CharField(max_length=100)
    book_code = models.CharField(max_length=100)
    title = models.CharField(max_length=400)
    author = models.CharField(max_length=400)
    book_read_url = models.URLField()
    subject = models.CharField(max_length=400)
    synopsis = models.TextField()
    category = models.ManyToManyField('Category', related_name='books')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.category_name}'


class BookLike(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book_likes')
    user = models.ForeignKey('UserProfile.Profile', on_delete=models.CASCADE, related_name='book_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class RequestedBook(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    book_url = models.URLField()
    reason = models.TextField()
    user = models.ForeignKey('UserProfile.Profile', on_delete=models.CASCADE, related_name='requested_books')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

KatalogBuku/forms.py
from django.forms import ModelForm
from .models import RequestedBook
from django import forms


class RequestedBookForm(ModelForm):
    class Meta:
        model = RequestedBook
        fields = ["title", "author", "book_url", "reason"]
        widgets = {
            "title": forms.TextInput(attrs={
                'class': 'text-[16px] rounded-[10px] px-2 py-1 border-[rgba(168, 168, 168, 0.5)] border-[1px] hover:border-[#727bfc] transition-all font-Inter'}),
            "author": forms.TextInput(attrs={
                'class': 'text-[16px] rounded-[10px] px-2 py-1 border-[rgba(168, 168, 168, 0.5)] border-[1px] hover:border-[#727bfc] transition-all font-Inter'}),
            "book_url": forms.TextInput(attrs={
                'class': 'text-[16px] rounded-[10px] px-2 py-1 border-[rgba(168, 168, 168, 0.5)] border-[1px] hover:border-[#727bfc] transition-all font-Inter'}),
            "reason": forms.Textarea(attrs={
                'class': 'text-[16px] rounded-[10px] px-2 py-1 border-[rgba(168, 168, 168, 0.5)] border-[1px] hover:border-[#727bfc] transition-all font-Inter'}),
            
        }

KatalogBuku/views.py
import datetime
from django.shortcuts import render
import json
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from .models import Book, Category, BookLike, RequestedBook
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from UserProfile.models import Profile
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from .forms import RequestedBookForm
from authentication.views import login_required_json


@require_http_methods(["GET"])
def index(request):
    user = request.user
    response = {"user": user}
    return render(request, "katalog.html", response)


@require_http_methods(["GET"])
def get_books(request):
    category = request.GET.get("category", None)
    sort = request.GET.get("sort", None)
    order = request.GET.get("order", None)
    page = request.GET.get("page", 1)
    search = request.GET.get("search", None)
    items_per_page = 20

    # Define allowed sort fields
    allowed_sort = ["issued", "title", "author", "subject", "category"]

    # Validate sort field
    if sort not in allowed_sort:
        sort = None

    # Validate order field
    if order not in ["asc", "desc"]:
        order = None

    # If sort field is defined, append order to it
    if sort is not None and order is not None:
        sort = f"{'' if order == 'asc' else '-'}{sort}"

    # Create a Q object for search
    search_query = Q(title__icontains=search) if search else Q()

    # Create a Q object for category
    category_query = Q(category__category_name=category) if category else Q()

    # Fetch books from the database
    books = (
        Book.objects.select_related("Category")
        .values(
            "id",
            "issued",
            "book_code",
            "title",
            "author",
            "book_read_url",
            "subject",
            "synopsis",
            "category__category_name",
        )
        .filter(search_query & category_query)
        .order_by(sort or "book_code")
    )

    # Paginate the results
    paginator = Paginator(books, items_per_page)
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    books_list = list(books)

    response = {
        "status": 200,
        "message": "success",
        "data": books_list,
        "pagination": {
            "current_page": books.number,
            "total_page": books.paginator.num_pages,
            "has_previous": books.has_previous(),
            "has_next": books.has_next(),
        },
    }
    return JsonResponse(response, status=200)


@require_http_methods(["GET"])
def get_categories(request):
    categories = Category.objects.values("id", "category_name").all()
    categories = list(categories)
    for category in categories:
        category["id"] = str(category["id"])

    response = {"status": 200, "message": "success", "data": categories}
    return HttpResponse(
        json.dumps(response), content_type="application/json", status=200
    )


@require_http_methods(["GET"])
@login_required_json
def get_book_by_id_json(request, book_id):
    try:
        user = request.user
        profile = Profile.objects.filter(user=user.id).first()
        if profile is None:
            return JsonResponse({"status": 400, "message": "Bad Request"}, status=400)
        book = (
            Book.objects.filter(id=book_id)
            .values(
                "id",
                "issued",
                "book_code",
                "title",
                "author",
                "book_read_url",
                "subject",
                "synopsis",
                "category__category_name",
            )
            .first()
        )
        if book is None:
            return JsonResponse(
                {"status": 404, "message": "Book not found"}, status=404
            )
        book["id"] = str(book["id"])
        book["category"] = book["category__category_name"]
        issued = book["issued"].split("-")
        issued = datetime.date(int(issued[0]), int(issued[1]), int(issued[2]))
        book["issued"] = issued.strftime("%d %B %Y")
        del book["category__category_name"]
        return JsonResponse(
            {"status": 200, "message": "success", "data": book}, status=200
        )

    except ValidationError as e:
        response = {
            "status": 400,
            "message": "Bad Request",
        }
        return JsonResponse(response, status=400)


@require_http_methods(["GET"])
@login_required(login_url="authentication:login")
def get_book_by_id(request, book_id):
    try:
        user = request.user
        profile = Profile.objects.filter(user=user.id).first()
        if profile is None:
            return HttpResponseRedirect(reverse("UserProfile:create_profile"))
        book = (
            Book.objects.filter(id=book_id)
            .values(
                "id",
                "issued",
                "book_code",
                "title",
                "author",
                "book_read_url",
                "subject",
                "synopsis",
                "category__category_name",
            )
            .first()
        )
        if book is None:
            response = {
                "status": 404,
                "message": "Book not found",
            }
            return HttpResponseRedirect(reverse("KatalogBuku:index"))
        book_like = BookLike.objects.filter(book=book["id"], user=profile).first()
        if book_like is None:
            book["is_liked"] = False
        else:
            book["is_liked"] = True

        book["id"] = str(book["id"])
        book["category"] = book["category__category_name"]
        issued = book["issued"].split("-")
        issued = datetime.date(int(issued[0]), int(issued[1]), int(issued[2]))
        book["issued"] = issued.strftime("%d %B %Y")
        del book["category__category_name"]

        book_like = BookLike.objects.filter(book=book["id"]).count()
        book["like"] = book_like
        response = {"status": 200, "message": "success", "data": book}
        return render(request, "detail-book.html", response)
    except ValidationError as e:
        response = {
            "status": 400,
            "message": "Bad Request",
        }
        return HttpResponseRedirect(reverse("KatalogBuku:index"))


@require_http_methods(["POST", "DELETE"])
@login_required()
@csrf_exempt
def like_book(request, book_id):
    user = request.user
    book = Book.objects.filter(id=book_id).first()
    profile = Profile.objects.filter(user=user.id).first()
    if book is None:
        response = {
            "status": 404,
            "message": "Book not found",
        }
        return HttpResponse(
            json.dumps(response), content_type="application/json", status=404
        )
    if request.method == "POST":
        book_like = BookLike.objects.filter(book=book, user=profile).first()
        if book_like is None:
            BookLike.objects.create(book=book, user=profile)
            response = {
                "status": 200,
                "message": "success",
            }
            return HttpResponse(
                json.dumps(response), content_type="application/json", status=200
            )
        else:
            response = {
                "status": 400,
                "message": "Book already liked",
            }
            return HttpResponse(
                json.dumps(response), content_type="application/json", status=400
            )
    if request.method == "DELETE":
        book_like = BookLike.objects.filter(book=book, user=profile).first()
        if book_like is None:
            response = {
                "status": 400,
                "message": "Book not liked",
            }
            return HttpResponse(
                json.dumps(response), content_type="application/json", status=400
            )
        else:
            book_like.delete()
            response = {
                "status": 200,
                "message": "success",
            }
            return HttpResponse(
                json.dumps(response), content_type="application/json", status=200
            )


@csrf_exempt
def unlike_book(request, book_id):
    user = request.user
    book = Book.objects.filter(id=book_id).first()
    profile = Profile.objects.filter(user=user.id).first()
    if book is None:
        response = {
            "status": 404,
            "message": "Book not found",
        }
        return HttpResponse(
            json.dumps(response), content_type="application/json", status=404
        )
    book_like = BookLike.objects.filter(book=book, user=profile).first()
    if book_like is None:
        response = {
            "status": 400,
            "message": "Book not liked",
        }
        return HttpResponse(
            json.dumps(response), content_type="application/json", status=400
        )
    else:
        book_like.delete()
        response = {
            "status": 200,
            "message": "success",
        }
        return HttpResponse(
            json.dumps(response), content_type="application/json", status=200
        )


@require_http_methods(["GET"])
@login_required(login_url="authentication:login")
def show_request_book(request):
    user = request.user
    profile = Profile.objects.filter(user=user.id).first()
    requests = RequestedBook.objects.values(
        "id", "title", "author", "reason", "user__username"
    ).all()
    response = {"profile": profile, "requests": requests}
    return render(request, "request_book.html", response)


@login_required(login_url="authentication:login")
def form_request_book(request):

KatalogBuku/templates/detail-book.html
{% extends 'base-tailwind.html' %} {% load static %} {% block content %}
{%include 'header.html' %}
<div class="relative py-4 lg:px-10 px-4 w-full">
  <div class="relative flex flex-col gap-4">
    <div class="w-[20%]">
      <button
        class="px-10 py-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter mt-4"
        id="back-button"
      >
        Back
      </button>
    </div>

    <div class="relative flex flex-col lg:flex-row gap-8">
      <div
        class="relative lg:w-[384px] lg:h-[384px] h-full w-fullbg-[#F5F7FA] rounded-[20px] shadow-md border-2 border-[#A9B7D1] p-[10px]"
      >
        <img
          src="{% static 'images/books/'|add:data.book_code|add:'.webp' %}"
          alt="{{ data.book_code }}"
          style="object-fit: contain; width: 101%; height: 101%"
        />
      </div>
      <div class="relative flex flex-col w-full gap-4">
        <h1 class="font-InterBold text-2xl">{{ data.title }}</h1>
        <p class="font-Inter text-gray-400 font-sm">{{ data.subject }}</p>
        <p class="font-Inter text-black font-md">{{ data.synopsis }}</p>
        <div class="flex flex-col gap-2">
          <p class="font-InterBold text-xl">Book Infromation:</p>
          <div
            class="font-Inter text-md p-2 rounded-[10px] border-2 border-[#A9B7D1] w-full gap-2 flex flex-col"
          >
            <p>Title : {{ data.title }}</p>
            <p>Author : {{ data.author }}</p>
            <p>Subject : {{ data.subject }}</p>
            <p>Issued Date : {{ data.issued }}</p>
          </div>
        </div>

        <div class="flex flex-col lg:flex-row lg:gap-4 gap-2">
          <button
            id="like-button"
            class="px-2 w-[100px] py-2 rounded-[10px] text-[16px] font-Inter mt-4 {% if data.is_liked %} text-black bg-gray-300 hover:bg-gray-400 {% else %} text-white bg-[#5068A9] hover:bg-[#738AB1] {% endif %}"
          >
            {% if data.is_liked %} Unlike : {{ data.like }} {% else %} Like : {{
            data.like }} {% endif %}
          </button>
          <button
            class="px-10 py-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter mt-4"
            id="read-button"
          >
            Read this book
          </button>
          <button
            class="px-10 py-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter mt-4"
            id="review-button"
          >
            Review this book
          </button>
          <button
            class="px-10 py-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter mt-4"
            id="see-review-button"
          >
            Read review for this book
          </button>
          <button
            class="px-10 py-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter mt-4"
            id="discussion-button"
          >
            Discussion for this Book
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'footer.html' %}

<script>
  const backButton = document.getElementById("back-button");
  backButton.addEventListener("click", () => {
    window.location.href = "{% url 'KatalogBuku:index' %}";
  });

  async function handleLike() {
    const isBookLiked = "{{ data.is_liked }}" === "True";
    if (!isBookLiked) {
      const id = "{{ data.id }}";
      const url =
        `{% url 'KatalogBuku:like_book' book_id="insert_id" %}`.replace(
          "insert_id",
          id
        );
      const response = await fetch(url, {
        method: "POST",
        "X-CSRFToken": "{{ csrf_token }}",
      });
      const data = await response.json();
      if (data.status === 200) {
        window.location.reload();
      }
    } else {
      const id = "{{ data.id }}";
      const url =
        `{% url 'KatalogBuku:like_book' book_id="insert_id" %}`.replace(
          "insert_id",
          id
        );
      const response = await fetch(url, {
        method: "DELETE",
        "X-CSRFToken": "{{ csrf_token }}",
      });
      const data = await response.json();
      if (data.status === 200) {
        window.location.reload();
      }
    }
  }

  async function handleReview() {
    const id = "{{ data.id }}";
    console.log("kesini");
    window.location.href =
      `{% url 'ReviewBuku:review_buku' book_id="insert_id" %}`.replace(
        "insert_id",
        id
      );
  }

  async function handleSeeReview() {
    const id = "{{ data.id }}";
    console.log("kesini");
    window.location.href =
      `{% url 'ReviewBuku:show_page_review_ajax' book_id="insert_id" %}`.replace(
        "insert_id",
        id
      );
  }

  async function handleDiscussion() {
    const id = "{{ data.id }}";
    window.location.href =
      `{% url 'ForumDiskusi:show_book_discussion' book_id="insert_id" %}`.replace(
        "insert_id",
        id
      );
  }

  const likeButton = document.getElementById("like-button");
  likeButton.addEventListener("click", handleLike);

  const reviewButton = document.getElementById("review-button");
  reviewButton.addEventListener("click", handleReview);

  const seeReviewButton = document.getElementById("see-review-button");
  seeReviewButton.addEventListener("click", handleSeeReview);

  const discussionButton = document.getElementById("discussion-button");
  discussionButton.addEventListener("click", handleDiscussion);
</script>
{% endblock content %}

KatalogBuku/templates/filter-modal.html
<div
        id="filterModal"
        tabindex="-1"
        aria-hidden="true"
        class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full"
>
    <div class="relative w-full max-w-2xl max-h-full">
        <div class="relative bg-white rounded-lg shadow">
            <div class="flex justify-between p-4 border-b rounded-t">
                <h3 class="text-xl font-InterBold text-black text-center">
                    Filter
                </h3>
                <button
                        type="button"
                        class="text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center hover:bg-gray-600 hover:text-white"
                        data-modal-hide="filterModal"
                >
                    <svg
                            class="w-3 h-3"
                            aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 14 14"
                    >
                        <path
                                stroke="currentColor"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>

            <div class="p-6 flex flex-col w-full justify-center">
                <h1 class="text-left font-InterBold text-md">Category</h1>
                <div class="relative grid grid-flow-row grid-cols-1 md:grid-cols-4 lg:grid-cols-3 md:gap-8 gap-6 mt-4"
                     id="categories-container">
                </div>
            </div>

            <div class="flex items-center justify-center p-6 space-x-2">
                <button
                        data-modal-hide="filterModal"
                        id="reset-filter-button"
                        class="p-2 rounded-[10px] text-[16px] text-white bg-[#D9534F] hover:bg-red-400 transition-all text-center font-Inter mt-4"
                >
                    Reset Filter
                </button>
                <button
                        data-modal-hide="filterModal"
                        type="button"
                        id="apply-filter-button"
                        class="p-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter mt-4"
                >
                    Apply Filter
                </button>
            </div>
        </div>
    </div>
</div>

KatalogBuku/templates/form-request.html
{% extends 'base-tailwind.html' %} {% load static %} {% block content %}
{%include 'header.html' %}
<div class="relative w-full px-4 lg:px-20 py-4">
  <div class="relative flex flex-col"></div>
  <h1 class="text-center font-InterBold text-3xl">Request a Book</h1>
  <form method="POST">
    {% csrf_token %}
    <div class="relative flex flex-col font-Inter text-md">
      {{ form }}
      <input
        type="submit"
        value="Request Book"
        class="p-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-InterBold mt-4 cursor-pointer"
      />
    </div>
  </form>
</div>

{% include 'footer.html' %} {% endblock content %}

KatalogBuku/templates/request_book.html
{% extends 'base-tailwind.html' %}

{% load static %}
{% block content %}
    {% include 'header.html' %}
    <div class="relative w-full px-4 lg:px-20 py-4 min-h-[500px]">
        <div class="relative flex flex-col gap-4">
            <h1 class="text-3xl font-bold text-center ">Requested Book</h1>

            <div class="relative flex flex-col justify-center items-center lg:items-start">
                <a href="{% url 'KatalogBuku:form_request_book' %}">
                    <button
                            class="px-4 py-2 rounded-[10px] text-[16px] text-white bg-[#5068A9] hover:bg-[#738AB1] transition-all text-center font-Inter"
                    >
                        Request a Book
                    </button>
                </a>
            </div>
            <div class="relative flex flex-col w-full gap-4">
                {% for request in requests %}
                    <div class="w-full border-2 rounded-[20px] bg-[#F5F7FA] shadow-sm hover:shadow-2xl transition-all flex flex-col p-[10px] gap-2">
                        <h1 class="font-InterBold text-xl line-clamp-1">{{ request.title }}</h1>
                        <h1 class="font-Inter text-md line-clamp-1">{{ request.author }}</h1>
                        <p class="font-Inter text-sm text-gray-400 line-clamp-1">Requested
                            by {{ request.user__username }}</p>
                        <p class="font-Inter text-md">Reason:</p>
                        <div class="relative w-full border-2 rounded-[10px] h-[100px] p-2">
                            <p class="font-Inter text-md line-clamp-3">{{ request.reason }}</p>
                        </div>
                    </div>


                {% endfor %}


            </div>

        </div>
    </div>

    {% include 'footer.html' %}
{% endblock content %}