KatalogBuku/urls.py
from django.urls import path
from .views import (
    index,
    get_books,
    get_categories,
    get_book_by_id,
    like_book,
    unlike_book,
    show_request_book,
    form_request_book,
    get_book_by_id_json,
)

app_name = "KatalogBuku"

urlpatterns = [
    path("", index, name="index"),
    path("books/", get_books, name="get_books"),
    path("books/category", get_categories, name="get_categories"),
    path("books/<str:book_id>", get_book_by_id, name="book_detail"),
    path("books/<str:book_id>/json", get_book_by_id_json, name="book_detail_json"),
    path("books/<str:book_id>/like", like_book, name="like_book"),
    path("books/<str:book_id>/unlike", unlike_book, name="unlike_book"),
    path("request/form", form_request_book, name="form_request_book"),
    path("request", show_request_book, name="show_request_book"),
]

README/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("KatalogBuku.urls")),
    path("__reload__/", include("django_browser_reload.urls")),  # new
    path("profile/", include("UserProfile.urls")),
    path("review/", include("ReviewBuku.urls")),
    path("", include("ForumDiskusi.urls")),
    path("read-book/", include("pinjambuku.urls")),
]

ReviewBuku/urls.py
from django.urls import path
from .views import *

app_name = "ReviewBuku"

urlpatterns = [
    path("", show_page_review, name="show_read_books"),
    path("add-review/<str:book_id>/", review_buku, name="review_buku"),
    path(
        "show-page-review-ajax/<str:book_id>/",
        show_page_review_ajax,
        name="show_page_review_ajax",
    ),
    path(
        "show-page-review-user-ajax/",
        show_page_review_user_ajax,
        name="show_page_review_user_ajax",
    ),
    path("get-reviews-json/", get_reviews_json, name="get_reviews_json"),
    path(
        "review-buku-flutter/",
        review_buku_flutter,
        name="review_buku_flutter",
    ),
]

UserProfile/urls.py
from django.urls import path
from .views import (
    create_profile_flutter,
    edit_profile_flutter,
    show_profile,
    create_profile,
    edit_profile,
    get_categories,
    show_profile_flutter,
)

app_name = "UserProfile"

urlpatterns = [
    path("", show_profile, name="show_profile"),
    path("create-profile/", create_profile, name="create_profile"),
    path("edit-profile/", edit_profile, name="edit_profile"),
    path("get-categories/", get_categories, name="get_categories"),
    path("show-profile/", show_profile_flutter, name="show_profile_flutter"),
    path(
        "create-profile-flutter/", create_profile_flutter, name="create_profile_flutter"
    ),
    path("edit-profile-flutter/", edit_profile_flutter, name="edit_profile_flutter"),
]

UserProfile/models.py
import uuid
from django.db import models
from authentication.models import User

app_name = 'UserProfile'

# Create your models here.
class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    profile_image = models.URLField()
    username = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    description = models.TextField()
    favorite_category = models.ForeignKey('KatalogBuku.Category', related_name='profiles', blank=True, null=True, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

UserProfile/forms.py
from django.forms import ModelForm, ModelChoiceField
from .models import Profile
from KatalogBuku.models import Category


class ProfileForm(ModelForm):
    favorite_category = ModelChoiceField(queryset=Category.objects.all(), to_field_name="category_name", required=False,
                                empty_label="Choose a category...")

    class Meta:
        model = Profile
        fields = ["profile_image", "username", "name", "description", "favorite_category"]

UserProfile/views.py
from django.shortcuts import render
from KatalogBuku.models import Category
from authentication.models import User
from .models import Profile
from .forms import ProfileForm
from django.http import (
    HttpResponse,
    HttpResponseNotFound,
    HttpResponseRedirect,
    JsonResponse,
)
from django.urls import reverse
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url="authentication:login")
def show_profile(request):
    context = {}

    try:
        profile = Profile.objects.get(user=request.user)
        context = {
            "profile_image": profile.profile_image,
            "username": profile.username,
            "name": profile.name,
            "description": profile.description,
            "favorite_category": profile.favorite_category,
        }
    except Profile.DoesNotExist:
        return HttpResponseRedirect(reverse("UserProfile:create_profile"))

    return render(request, "user_profile.html", context)


@login_required(login_url="authentication:login")
def create_profile(request):
    existing_profile = Profile.objects.filter(user=request.user).first()
    if existing_profile:
        return HttpResponseRedirect(reverse("KatalogBuku:index"))

    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return HttpResponseRedirect(reverse("KatalogBuku:index"))
    else:
        form = ProfileForm()

    context = {"form": form}
    return render(request, "create_profile.html", context)


@csrf_exempt
@login_required(login_url="authentication:login")
def edit_profile(request):
    if request.method == "POST":
        try:
            profile = Profile.objects.get(user=request.user)
        except Profile.DoesNotExist:
            profile = Profile(user=request.user)
        favorite_category = Category.objects.get(
            id=request.POST.get("favorite_category")
        )
        profile_image = request.POST.get("profile_image")
        username = request.POST.get("username")
        name = request.POST.get("name")
        description = request.POST.get("description")
        profile.profile_image = profile_image
        profile.username = username
        profile.name = name
        profile.description = description
        profile.favorite_category = favorite_category

        profile.save()

        return HttpResponse(b"OK", status=200)

    return HttpResponseNotFound(b"Invalid request method", status=400)


def get_categories(request):
    categories = Category.objects.all().values("id", "category_name")
    return JsonResponse(list(categories), safe=False)


def show_profile_flutter(request):
    profile = Profile.objects.get(user=request.user)
    if profile is None:
        return JsonResponse({"status": "error"}, status=400)
    profile_dict = model_to_dict(profile)

    response = {
        "model": "Profile",
        "pk": profile.id,
        "fields": profile_dict,
    }

    return JsonResponse(response, status=200)


@csrf_exempt
def create_profile_flutter(request):
    if request.method == "POST":
        existing_profile = Profile.objects.filter(user=request.user).first()
        if existing_profile:
            return JsonResponse({"status": "error"}, status=400)
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return JsonResponse({"status": "success"}, status=200)
        return JsonResponse({"status": "error"}, status=400)
    else:
        return JsonResponse({"status": "error"}, status=400)


@csrf_exempt
def edit_profile_flutter(request):
    if request.method == "POST":
        profile_image = request.POST.get("profile_image")
        username = request.POST.get("username")
        name = request.POST.get("name")
        description = request.POST.get("description")
        favorite_category_name = request.POST.get("favorite_category")

        try:
            profile = Profile.objects.get(user=request.user)
            category = Category.objects.get(category_name=favorite_category_name)

            profile.profile_image = profile_image
            profile.username = username
            profile.name = name
            profile.description = description
            profile.favorite_category = category
            profile.save()

            return JsonResponse({"status": "success"}, status=200)
        except Category.DoesNotExist:
            return JsonResponse(
                {"status": "error", "message": "Category does not exist"}, status=400
            )
        except Profile.DoesNotExist:
            return JsonResponse(
                {"status": "error", "message": "Profile does not exist"}, status=400
            )
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=500)

UserProfile/templates/create_profile.html
{% extends 'base-bootstrap.html' %}

{% load static %}

{% block meta %}
    <title>Create Profile</title>
{% endblock meta %}

{% block content %}
    <div class="createbox">
        {% include 'header.html' %}
        <h1 style="margin-bottom: 20px;margin-top: 20px">Create Profile</h1>
        <div class="createform" style="margin-bottom: 20px">
            <form method="POST">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td>
                            <input class="createbutton" type="submit" value="Create Profile"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        {% include 'footer.html' %}
    </div>
{% endblock %}

UserProfile/templates/user_profile.html
{% extends 'base-bootstrap.html' %}

{% load static %}

{% block meta %}
    <title>{{ username }}</title>
{% endblock meta %}

{% block content %}

    {% include 'header.html' %}
    <div class="container-profile">
        <div class="profilebox">
            <img class="imageprofile" src="{{ profile_image }}" alt="{{ username }}"/>
            <div class="name_attributes">
                <p style="font-size: 18px;">{{ username }}</p>
                <h1 style="margin-top: -15px; margin-bottom: 20px; font-weight: 600;">{{ name }}</h1>
                <p>{{ description }}</p>
            </div>
            <div class="descfav_attributes">
                <p style="font-size: 14px;">Favorite Category</p>
                <h2 style="font-weight: 700;">{{ favorite_category }}</h2>
            </div>
        </div>
        <button class="editprofile" type="button" id="editButton">Edit Profile</button>

        <div class="edit-form-container">
            <div class="col-md-6">
                <form id="editProfileForm" style="display: none;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="col-form-label">Profile Image</label>
                        <input type="url" class="form-control" id="profile_image" name="profile_image"
                               value="{{ profile_image }}">
                    </div>
                    <div class="mb-3">
                        <label for="username" class="col-form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{ username }}">
                    </div>
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ name }}">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description</label>
                        <textarea class="form-control" id="description" name="description">{{ description }}</textarea>
                    </div>
                    <div class="mb-3">
                        <label for="favorite_category" class="col-form-label">Favorite Category</label>
                        <select class="form-control" id="favorite_category" name="favorite_category">
                            <option value="" disabled selected>Choose a category...</option>
                        </select>
                    </div>
                    <button type="button" id="button_save_profile">Save</button>
                </form>
            </div>
        </div>
        <hr>

        <button class="underbutton">
            <a href="{% url 'KatalogBuku:index' %}">My Books</a>
        </button>

        <button class="underbutton">
            <a href="{% url 'ReviewBuku:show_page_review_user_ajax' %}">See My Reviews</a>
        </button>
    </div>

    {% include 'footer.html' %}

    <script>
        const editButton = document.getElementById('editButton');
        const editForm = document.getElementById('editProfileForm');

        editButton.addEventListener('click', function () {
            if (editForm.style.display === 'none') {
                editForm.style.display = 'block';
                editButton.innerText = 'Cancel';
                loadCategories();
            } else {
                editForm.style.display = 'none';
                editButton.innerText = 'Edit Profile';
            }
        });

        document.getElementById('button_save_profile').addEventListener('click', function () {
            const formData = new FormData();
            formData.append('profile_image', document.getElementById('profile_image').value);
            formData.append('username', document.getElementById('username').value);
            formData.append('name', document.getElementById('name').value);
            formData.append('description', document.getElementById('description').value);
            formData.append('favorite_category', document.getElementById('favorite_category').value);

            fetch('/profile/edit-profile/', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': getCookie('csrftoken')
                }
            })
                .then(response => {
                    if (response.status === 200) {
                        alert('Profile updated successfully');
                        editForm.style.display = 'block';
                        editButton.innerText = 'Cancel';
                        window.location.reload()
                    } else if (response.status === 404) {
                        alert('Profile not found');
                    } else {
                        alert('Profile update failed');
                    }
                })
                .catch(error => {
                    console.error('An error occurred:', error);
                });
        });

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function loadCategories() {
            fetch('{% url "UserProfile:get_categories" %}')
                .then(response => response.json())
                .then(data => {
                    const selectCategory = document.getElementById('favorite_category');
                    selectCategory.innerHTML = "";

                    data.forEach(category => {
                        const option = document.createElement('option');
                        option.value = category.id;
                        option.text = category.category_name;
                        if (category.category_name === "{{favorite_category}}") {
                            option.selected = true
                        }
                        selectCategory.appendChild(option);
                    });
                })
                .catch(error => {
                    console.error('Error loading categories:', error);
                });
        }

        loadCategories();
    </script>
{% endblock %}