KatalogBuku/urls.py
from django.urls import path
from .views import (
    index,
    get_books,
    get_categories,
    get_book_by_id,
    like_book,
    unlike_book,
    show_request_book,
    form_request_book,
    get_book_by_id_json,
)

app_name = "KatalogBuku"

urlpatterns = [
    path("", index, name="index"),
    path("books/", get_books, name="get_books"),
    path("books/category", get_categories, name="get_categories"),
    path("books/<str:book_id>", get_book_by_id, name="book_detail"),
    path("books/<str:book_id>/json", get_book_by_id_json, name="book_detail_json"),
    path("books/<str:book_id>/like", like_book, name="like_book"),
    path("books/<str:book_id>/unlike", unlike_book, name="unlike_book"),
    path("request/form", form_request_book, name="form_request_book"),
    path("request", show_request_book, name="show_request_book"),
]

README/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("KatalogBuku.urls")),
    path("__reload__/", include("django_browser_reload.urls")),  # new
    path("profile/", include("UserProfile.urls")),
    path("review/", include("ReviewBuku.urls")),
    path("", include("ForumDiskusi.urls")),
    path("read-book/", include("pinjambuku.urls")),
]

UserProfile/urls.py
from django.urls import path
from .views import (
    create_profile_flutter,
    edit_profile_flutter,
    show_profile,
    create_profile,
    edit_profile,
    get_categories,
    show_profile_flutter,
)

app_name = "UserProfile"

urlpatterns = [
    path("", show_profile, name="show_profile"),
    path("create-profile/", create_profile, name="create_profile"),
    path("edit-profile/", edit_profile, name="edit_profile"),
    path("get-categories/", get_categories, name="get_categories"),
    path("show-profile/", show_profile_flutter, name="show_profile_flutter"),
    path(
        "create-profile-flutter/", create_profile_flutter, name="create_profile_flutter"
    ),
    path("edit-profile-flutter/", edit_profile_flutter, name="edit_profile_flutter"),
]

authentication/urls.py
from django.urls import path
from .views import (
    user_login,
    user_register,
    user_logout,
    cookie_logout,
    check_login,
    check_auth,
)

app_name = "authentication"

urlpatterns = [
    path("login/", user_login, name="login"),
    path("register/", user_register, name="register"),
    path("logout/", user_logout, name="logout"),
    path("cookie-logout/", cookie_logout, name="cookie-logout"),
    path("login/check/", check_login, name="check-login"),
    path("protected/", check_auth, name="check-auth"),
]

templates/base-bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% endblock meta %}

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/index.css' %}"/>
    {% endblock css %}

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
    />

    <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
    ></script>
    <title>ReadMe</title>
</head>

<body class=" scrollbar-hide">
<div style="width: 100%;min-height: 100vh">
    {% block content %} {% endblock content %}
</div>
</body>
</html>

templates/base-tailwind.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% endblock meta %}

    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'styles/tailwind.css' %}"
    />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/index.css' %}"/>
    <title>ReadMe</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
</head>
<body class="bg-[#F5F7FA] scrollbar-hide">
<div class="w-full min-h-screen">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

templates/footer.html
{% load static %}
<style>

    .footer-container {
        width: 100%;
        display: flex;
        flex-direction: column;
        padding: 32px 20px;
        position: relative;
        background-color: #5068A9;
        gap: 20px;
    }

    .footer-container p {
        color: white;
        font-family: Inter, sans-serif;
        font-size: 16px;

    }

    @media only screen and (max-width: 600px) {
        .footer-container {
            padding-top: 20px;
            padding-bottom: 20px;
        }
    }

    .content-container {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
    }

    .logo-container {
        width: 100px;
        height: 100px;
    }

    .nav-container {
        width: 100%;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
    }

    .nav-container a {
        text-decoration: none;
        color: white;
        font-family: InterBold, sans-serif;
        font-size: 16px;
    }
</style>
<div class="footer-container">
    <div class="content-container">
        <div class="nav-container">
            
        </div>
        <div class="logo-container">
            <a href="{% url 'KatalogBuku:index' %}">
                <img src="{% static 'images/logo.png' %}" alt="logo" width="100%" height="100%"/>
            </a>
        </div>
    </div>
    <div>
        <p>Made with &#10084; by PBP-F04 2023</p>
        <p>© PBP-F04 2023</p>

    </div>

</div>

templates/header.html
{% load static %}
<style>
    .nav-container {
        width: 100%;
        background-color: #5068A9;
        display: flex;
        padding: 8px 16px;
        align-items: center;
        justify-content: space-between;
        z-index: 1;
    }

    .navbar-text {
        color: white;
        font-size: 16px;
        font-family: "Inter", serif;
        display: flex;
        gap: 20px;
    }

    .nav-text {
        text-decoration-line: none;
        transition: all 0.3s ease-in-out;
    }

    .nav-text:hover {
        text-decoration-line: underline;
        transition: all 0.3s ease-in-out;
    }

    .login-button {
        background-color: #F5F7FA;
        color: black;
        border: none;
        border-radius: 8px;
        padding: 8px 16px;
        font-size: 16px;
        font-family: "InterBold", serif;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .login-button:hover {
        background-color: #A9B7D1;
        transition: all 0.3s ease-in-out;
    }

    @media only screen and (max-width: 1023px) {
        .navbar-text {
            display: none;
        }

        .dropdown-content {
            display: none;
        }

        #menu-dropdown:active + .dropdown-content {
            display: block;
        }
    }

    .dropdown-content {
        display: none;
        flex-direction: column;
        background-color: #5068A9;
        width: 100%;
        z-index: 1;
    }

    .dropdown-content a {
        color: white;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1;
        color: black;
    }

</style>

<div class="nav-container">
    <a href="{% url 'KatalogBuku:index' %}">
        <img src="{% static 'images/logo.png' %}" alt="logo" width="45px" height="45px" style="object-fit: contain">
    </a>

    <div class="navbar-text" id="nav-body">
        <a class="nav-text" href="{% url 'KatalogBuku:index' %}">Home</a>
        <a class="nav-text" href="{% url 'KatalogBuku:show_request_book' %}">Request Book</a>
        <a class="nav-text" href="{% url 'UserProfile:show_profile' %}">Profile</a>


    </div>

    <div>
        <a href="{% url 'authentication:login' %}" id="a-login-button">
            <button class="login-button" id="login-button">Login</button>
        </a>
    </div>

    <div id="menu-dropdown">
        <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 16 16"
                style="fill: white; width: 30px; height: 30px; cursor: pointer;"
        >
            <path
                    fill-rule="evenodd"
                    d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
        </svg>
    </div>

</div>
<div class="dropdown-content" id="dropdown">
    <a href="{% url 'KatalogBuku:index' %}">Home</a>
    <a href="{% url 'KatalogBuku:show_request_book' %}">Request Book</a>
    <a href="{% url 'UserProfile:show_profile' %}">Profile</a>


    <div style="text-align: center">
        <a href="{% url 'authentication:login' %}" id="a-login-button-mobile">
            <button class="login-button" id="login-button-mobile" style="width: 75%">Login</button>
        </a></div>

</div>


<script>
    function removeLoginButtonMobile() {
        if (window.innerWidth < 1023) {
            let loginButton = document.getElementById("login-button");
            loginButton.remove();
        }
    }

    function addLoginButtonMobile() {
        const loginButtonHtml = `  <div>
        <a href="{% url 'authentication:login' %}">
            <button class="login-button" id="login-button">Login</button>
        </a>`
        if (window.innerWidth < 1023) {
            let navBody = document.getElementById("nav-body");
            navBody.innerHTML += loginButtonHtml;
            const loginButton = document.getElementById("login-button");
            loginButton.style.width = "100%";
        }
    }

    function removeMenuDropdown() {
        if (window.innerWidth > 1023) {
            let menuDropdown = document.getElementById("menu-dropdown");
            menuDropdown.remove();
        }
    }

    function expandDropdown() {
        document.getElementById("menu-dropdown").onclick = function () {
            const dropdown = document.getElementById("dropdown");
            const mainContainer = document.getElementsByClassName("nav-container");


            if (dropdown.style.display === "none" || dropdown.style.display === "") {
                dropdown.style.display = "block";
                dropdown.style.position = "absolute";

            } else {
                dropdown.style.display = "none";


            }

        }
    }

    expandDropdown();
    removeLoginButtonMobile();
    removeMenuDropdown();
    addLoginButtonMobile()

</script>

{% if user.is_authenticated %}
    <script>
        const loginButton = document.getElementById("login-button");
        const aLoginButton = document.getElementById("a-login-button");
        aLoginButton.href = "{% url 'authentication:logout' %}";
        loginButton.innerHTML = "Logout";
        const loginButtonMobile = document.getElementById("login-button-mobile");
        const aLoginButtonMobile = document.getElementById("a-login-button-mobile");
        aLoginButtonMobile.href = "{% url 'authentication:logout' %}";
        loginButtonMobile.innerHTML = "Logout";
    </script>
{% endif %}